### ISSUE TITLE
Add `--skip-length-validation-and-pad` flag. 🏁

### ISSUE THREAD

**Issue by michaelbeutler** [truvami/decoder#13]
Add a CLI flag, `--skip-length-validation-and-pad`, that bypasses length validation and automatically pads the input with leading zeros to meet the required length. This feature would be beneficial for users who want to ensure inputs meet a specified length requirement without manually adjusting the input.

**Proposed Behavior**
When the `--skip-length-validation-and-pad` flag is used:
- Length validation on input should be bypassed.
- If the input is shorter than the required length, it should be padded with leading zeros to meet the length requirement.
  - For example, with a required length of 8, an input of `123` should be transformed into `00000123`.

**Use Case**
This feature would be particularly useful in cases where input length requirements are enforced but may vary, and users need a quick way to automatically adjust input without additional scripting.

**Example Usage**
```bash
decoder tagsl 15 123 --skip-length-validation-and-pad
# Expected outcome: payload processed as 00000123
```

**Comment by simylein** [comment]
I would like to be assigned to this issue
